export const DEFAULT_BUTTON_LAYOUT = [
  { name: 'Initialize', handler: 'initializeRtc' },
  { name: 'Join', handler: 'joinRtcChannel' },
  { name: 'Leave', handler: 'leaveRtcChannel' },
  { name: 'Preview', handler: 'togglePreview' },
  { name: 'Views', handler: 'refreshRtcViews' },
  { name: 'Speaker', handler: 'toggleSpeakerphone' },
  { name: 'Mic', handler: 'toggleLocalAudio' },
  { name: 'Cam', handler: 'toggleLocalVideo' },
  { name: 'Full Demo', handler: 'runCapabilityDemo' },
  { name: 'Channel', handler: 'runChannelRoleDemo' },
  { name: 'Mixing', handler: 'runMixingDemo' },
  { name: 'Effect', handler: 'runEffectDemo' },
  { name: 'Diag', handler: 'runDiagnosticsDemo' },
  { name: 'Profile', handler: 'cycleChannelProfilePreset' },
  { name: 'Role', handler: 'cycleClientRolePreset' },
  { name: 'Encoder', handler: 'cycleVideoEncoderPreset' },
  { name: 'Freeze', handler: 'toggleStatusFreeze' },
  { name: 'Clear', handler: 'clearStatusLog' },
  { name: 'EnableAudio', handler: 'toggleEnableAudio' },
  { name: 'EnableLocalAudio', handler: 'toggleEnableLocalAudio' },
  { name: 'MuteLocalAudio', handler: 'toggleMuteLocalAudio' },
  { name: 'MuteRemoteAudio', handler: 'toggleMuteRemoteAudio' },
  { name: 'MuteAllRemoteAudio', handler: 'toggleMuteAllRemoteAudio' },
  { name: 'AudioVolumeIndication', handler: 'toggleAudioVolumeIndication' },
  { name: 'DefaultAudioRoute', handler: 'toggleDefaultAudioRoute' },
  { name: 'PlaybackVolume', handler: 'togglePlaybackVolume' },
  { name: 'AudioProfile', handler: 'toggleAudioProfile' },
  { name: 'EnableVideo', handler: 'toggleEnableVideo' },
  { name: 'MuteLocalVideo', handler: 'toggleMuteLocalVideo' },
  { name: 'MuteRemoteVideo', handler: 'toggleMuteRemoteVideo' },
  { name: 'MuteAllRemoteVideo', handler: 'toggleMuteAllRemoteVideo' },
  { name: 'SwitchCamera', handler: 'triggerSwitchCamera' },
  { name: 'BeautyEffect', handler: 'toggleBeautyEffect' },
  { name: 'ContentInspect', handler: 'toggleContentInspect' },
  { name: 'PlaybackUserVolume', handler: 'togglePlaybackUserVolume' },
] as const;

export const SESSION_QUICK_BUTTONS = ['Initialize', 'Join', 'Leave'] as const;

export const BUTTON_SECTION_LAYOUT = [
  { title: 'Session', buttons: ['Preview', 'Views', 'Full Demo'] },
  { title: 'Render', buttons: ['Speaker', 'Mic', 'Cam'] },
  { title: 'Audio API', buttons: [
    'EnableAudio',
    'EnableLocalAudio',
    'MuteLocalAudio',
    'MuteRemoteAudio',
    'MuteAllRemoteAudio',
    'AudioVolumeIndication',
    'DefaultAudioRoute',
    'PlaybackVolume',
    'AudioProfile',
  ] },
  { title: 'Video API', buttons: [
    'EnableVideo',
    'MuteLocalVideo',
    'MuteRemoteVideo',
    'MuteAllRemoteVideo',
    'SwitchCamera',
    'BeautyEffect',
    'ContentInspect',
    'PlaybackUserVolume',
  ] },
  { title: 'Mixer', buttons: ['Mixing', 'Effect', 'Diag'] },
  { title: 'Tools', buttons: ['Freeze', 'Clear'] },
] as const;

export const ACTION_LABELS: Record<string, string> = {
  Initialize: 'Initialize',
  Join: 'Join',
  Leave: 'Leave',
  Preview: 'Preview',
  Views: 'Views',
  Speaker: 'Speaker',
  Mic: 'Mic',
  Cam: 'Cam',
  'Full Demo': 'Full Demo',
  Mixing: 'Mixing',
  Effect: 'Effect',
  Diag: 'Diagnostics',
  Freeze: 'Freeze Log',
  Clear: 'Clear Log',
  Channel: 'Channel Demo',
  Profile: 'Profile',
  Role: 'Role',
  Encoder: 'Encoder',
  EnableAudio: 'Enable Audio',
  EnableLocalAudio: 'Local Audio',
  MuteLocalAudio: 'Mute Local Audio',
  MuteRemoteAudio: 'Mute Remote Audio',
  MuteAllRemoteAudio: 'Mute All Remote',
  AudioVolumeIndication: 'Volume Indicator',
  DefaultAudioRoute: 'Default Route',
  PlaybackVolume: 'Playback Volume',
  AudioProfile: 'Audio Profile',
  EnableVideo: 'Enable Video',
  MuteLocalVideo: 'Mute Local Video',
  MuteRemoteVideo: 'Mute Remote Video',
  MuteAllRemoteVideo: 'Mute All Remote',
  SwitchCamera: 'Switch Camera',
  BeautyEffect: 'Beauty Effect',
  ContentInspect: 'Content Inspect',
  PlaybackUserVolume: 'User Volume',
};

export type DemoActionName = typeof DEFAULT_BUTTON_LAYOUT[number]['name'];
export type DemoActionHandlerName = typeof DEFAULT_BUTTON_LAYOUT[number]['handler'];
