import {
  AgoraAudioProfile,
  AgoraAudioScenario,
  type AgoraRtcClient,
} from '../../../extensions/agora-rtc/js/agora.ts';

export type ApiEvidenceKind = 'response' | 'event' | 'error' | 'value';

export type ApiTestContext = {
  appId: string;
  token: string;
  channelId: string;
  uid: number;
  logFilePath: string;
  audioAssetPath: string;
};

export type ApiCallCase = {
  id: string;
  method: string;
  expectedParams: Record<string, unknown>;
  requiredEvidence: ApiEvidenceKind[];
  run: (client: AgoraRtcClient, context: ApiTestContext) => Promise<unknown>;
};

const remoteUid = 42422;
const userAccount = 'cocos-user-0';
const wait = (ms: number) => new Promise<void>((resolve) => setTimeout(resolve, ms));
const canvas = {
  x: 24,
  y: 32,
  width: 240,
  height: 180,
  renderMode: 'fit' as const,
  mirrorMode: 2,
  setupMode: 0,
  sourceType: 0,
  position: 1,
  textureWidth: 240,
  textureHeight: 180,
};

export const API_CALL_TESTCASES: ApiCallCase[] = [
  {
    id: 'engine.initialize',
    method: 'initialize',
    expectedParams: { appId: '<TEST_APP_ID>' },
    requiredEvidence: ['response'],
    run: (client, context) => client.initialize(context.appId),
  },
  {
    id: 'engine.set-render-backend',
    method: 'setRenderBackend',
    expectedParams: { backend: 'engine-texture' },
    requiredEvidence: ['response'],
    run: (client) => client.setRenderBackend('engine-texture'),
  },
  {
    id: 'engine.get-sdk-version',
    method: 'getSdkVersion',
    expectedParams: {},
    requiredEvidence: ['value'],
    run: (client) => client.getSdkVersion(),
  },
  {
    id: 'engine.get-error-description',
    method: 'getErrorDescription',
    expectedParams: { code: 0 },
    requiredEvidence: ['value'],
    run: (client) => client.getErrorDescription(0),
  },
  {
    id: 'engine.set-log-filter',
    method: 'setLogFilter',
    expectedParams: { level: 15 },
    requiredEvidence: ['response'],
    run: (client) => client.setLogFilter(15),
  },
  {
    id: 'engine.set-log-file',
    method: 'setLogFile',
    expectedParams: { path: '<WRITABLE>/agora-cocos-api-test.log' },
    requiredEvidence: ['response'],
    run: (client, context) => client.setLogFile(context.logFilePath),
  },
  {
    id: 'engine.set-parameters',
    method: 'setParameters',
    expectedParams: { parameters: '{"che.audio.keep.audiosession":true}' },
    requiredEvidence: ['response'],
    run: (client) => client.setParameters('{"che.audio.keep.audiosession":true}'),
  },
  {
    id: 'channel.set-profile',
    method: 'setChannelProfile',
    expectedParams: { profile: 'liveBroadcasting' },
    requiredEvidence: ['response'],
    run: (client) => client.setChannelProfile('liveBroadcasting'),
  },
  {
    id: 'channel.set-client-role',
    method: 'setClientRole',
    expectedParams: { role: 'broadcaster' },
    requiredEvidence: ['response'],
    run: (client) => client.setClientRole('broadcaster'),
  },
  {
    id: 'channel.join-user-account',
    method: 'joinChannelWithUserAccount',
    expectedParams: {
      token: '<TEST_TOKEN>',
      channelId: '<TEST_CHANNEL_ID>',
      userAccount,
      options: {
        publishCameraTrack: false,
        publishMicrophoneTrack: false,
        autoSubscribeAudio: true,
        autoSubscribeVideo: true,
      },
    },
    requiredEvidence: ['response', 'event', 'error'],
    run: (client, context) => client.joinChannelWithUserAccount(context.token, context.channelId, userAccount, {
      publishCameraTrack: false,
      publishMicrophoneTrack: false,
      autoSubscribeAudio: true,
      autoSubscribeVideo: true,
    }),
  },
  {
    id: 'channel.get-user-info-by-user-account',
    method: 'getUserInfoByUserAccount',
    expectedParams: { userAccount },
    requiredEvidence: ['value', 'error'],
    run: (client) => client.getUserInfoByUserAccount(userAccount),
  },
  {
    id: 'channel.leave-user-account',
    method: 'leaveChannel',
    expectedParams: {
      stopAudioMixing: false,
      stopAllEffect: false,
      unloadAllEffect: false,
      stopMicrophoneRecording: false,
    },
    requiredEvidence: ['response', 'event', 'error'],
    run: (client) => client.leaveChannel({
      stopAudioMixing: false,
      stopAllEffect: false,
      unloadAllEffect: false,
      stopMicrophoneRecording: false,
    }),
  },
  {
    id: 'channel.join',
    method: 'joinChannel',
    expectedParams: {
      token: '<TEST_TOKEN>',
      channelId: '<TEST_CHANNEL_ID>',
      uid: '<TEST_UID>',
      options: {
        clientRoleType: 'broadcaster',
        channelProfile: 'liveBroadcasting',
        publishCameraTrack: true,
        publishMicrophoneTrack: false,
        autoSubscribeAudio: true,
        autoSubscribeVideo: true,
        startPreview: true,
        sourceType: 0,
      },
    },
    requiredEvidence: ['response', 'event'],
    run: (client, context) => client.joinChannel(context.token, context.channelId, context.uid, {
      clientRoleType: 'broadcaster',
      channelProfile: 'liveBroadcasting',
      publishCameraTrack: true,
      publishMicrophoneTrack: false,
      autoSubscribeAudio: true,
      autoSubscribeVideo: true,
      startPreview: true,
      sourceType: 0,
    }),
  },
  {
    id: 'channel.renew-token',
    method: 'renewToken',
    expectedParams: { token: '<TEST_TOKEN>' },
    requiredEvidence: ['response', 'error'],
    run: (client, context) => client.renewToken(context.token),
  },
  {
    id: 'audio.enable',
    method: 'enableAudio',
    expectedParams: { enabled: true },
    requiredEvidence: ['response'],
    run: (client) => client.enableAudio(true),
  },
  {
    id: 'audio.enable-local',
    method: 'enableLocalAudio',
    expectedParams: { enabled: true },
    requiredEvidence: ['response'],
    run: (client) => client.enableLocalAudio(true),
  },
  {
    id: 'audio.mute-local',
    method: 'muteLocalAudioStream',
    expectedParams: { muted: false },
    requiredEvidence: ['response'],
    run: (client) => client.muteLocalAudioStream(false),
  },
  {
    id: 'audio.mute-remote',
    method: 'muteRemoteAudioStream',
    expectedParams: { uid: remoteUid, muted: true },
    requiredEvidence: ['response'],
    run: (client) => client.muteRemoteAudioStream(remoteUid, true),
  },
  {
    id: 'audio.mute-all-remote',
    method: 'muteAllRemoteAudioStreams',
    expectedParams: { muted: false },
    requiredEvidence: ['response'],
    run: (client) => client.muteAllRemoteAudioStreams(false),
  },
  {
    id: 'audio.profile',
    method: 'setAudioProfile',
    expectedParams: { profile: 5, scenario: 3 },
    requiredEvidence: ['response'],
    run: (client) => client.setAudioProfile(
      AgoraAudioProfile.MusicHighQualityStereo,
      AgoraAudioScenario.GameStreaming,
    ),
  },
  {
    id: 'audio.volume-indication',
    method: 'enableAudioVolumeIndication',
    expectedParams: { interval: 200, smooth: 3, reportVad: true },
    requiredEvidence: ['response'],
    run: (client) => client.enableAudioVolumeIndication(200, 3, true),
  },
  {
    id: 'audio.default-speaker-route',
    method: 'setDefaultAudioRouteToSpeakerphone',
    expectedParams: { enabled: true },
    requiredEvidence: ['response', 'error'],
    run: (client) => client.setDefaultAudioRouteToSpeakerphone(true),
  },
  {
    id: 'audio.set-speakerphone',
    method: 'setEnableSpeakerphone',
    expectedParams: { enabled: true },
    requiredEvidence: ['response', 'error'],
    run: (client) => client.setEnableSpeakerphone(true),
  },
  {
    id: 'audio.is-speakerphone-enabled',
    method: 'isSpeakerphoneEnabled',
    expectedParams: {},
    requiredEvidence: ['value'],
    run: (client) => client.isSpeakerphoneEnabled(),
  },
  {
    id: 'audio.adjust-playback-volume',
    method: 'adjustPlaybackSignalVolume',
    expectedParams: { volume: 80 },
    requiredEvidence: ['response'],
    run: (client) => client.adjustPlaybackSignalVolume(80),
  },
  {
    id: 'audio.adjust-user-playback-volume',
    method: 'adjustUserPlaybackSignalVolume',
    expectedParams: { uid: remoteUid, volume: 70 },
    requiredEvidence: ['response'],
    run: (client) => client.adjustUserPlaybackSignalVolume(remoteUid, 70),
  },
  {
    id: 'audio.session-restriction',
    method: 'setAudioSessionOperationRestriction',
    expectedParams: { restriction: 1 },
    requiredEvidence: ['response', 'error'],
    run: (client) => client.setAudioSessionOperationRestriction(1),
  },
  {
    id: 'video.enable',
    method: 'enableVideo',
    expectedParams: { enabled: true },
    requiredEvidence: ['response'],
    run: (client) => client.enableVideo(true),
  },
  {
    id: 'video.enable-local',
    method: 'enableLocalVideo',
    expectedParams: { enabled: true },
    requiredEvidence: ['response'],
    run: (client) => client.enableLocalVideo(true),
  },
  {
    id: 'video.mute-local',
    method: 'muteLocalVideoStream',
    expectedParams: { muted: false },
    requiredEvidence: ['response'],
    run: (client) => client.muteLocalVideoStream(false),
  },
  {
    id: 'video.mute-remote',
    method: 'muteRemoteVideoStream',
    expectedParams: { uid: remoteUid, muted: true },
    requiredEvidence: ['response'],
    run: (client) => client.muteRemoteVideoStream(remoteUid, true),
  },
  {
    id: 'video.mute-all-remote',
    method: 'muteAllRemoteVideoStreams',
    expectedParams: { muted: false },
    requiredEvidence: ['response'],
    run: (client) => client.muteAllRemoteVideoStreams(false),
  },
  {
    id: 'video.encoder-config',
    method: 'setVideoEncoderConfiguration',
    expectedParams: { width: 640, height: 360, frameRate: 15, bitrate: 0, orientationMode: 0 },
    requiredEvidence: ['response'],
    run: (client) => client.setVideoEncoderConfiguration({
      width: 640,
      height: 360,
      frameRate: 15,
      bitrate: 0,
      orientationMode: 0,
    }),
  },
  {
    id: 'render.setup-local-view',
    method: 'setupLocalVideoView',
    expectedParams: canvas,
    requiredEvidence: ['response'],
    run: (client) => client.setupLocalVideoView(canvas),
  },
  {
    id: 'render.setup-remote-view',
    method: 'setupRemoteVideoView',
    expectedParams: { uid: remoteUid, ...canvas },
    requiredEvidence: ['response'],
    run: (client) => client.setupRemoteVideoView(remoteUid, canvas),
  },
  {
    id: 'render.update-local-view',
    method: 'updateLocalVideoView',
    expectedParams: { ...canvas, x: 36 },
    requiredEvidence: ['response'],
    run: (client) => client.updateLocalVideoView({ ...canvas, x: 36 }),
  },
  {
    id: 'render.update-remote-view',
    method: 'updateRemoteVideoView',
    expectedParams: { uid: remoteUid, ...canvas, x: 48 },
    requiredEvidence: ['response'],
    run: (client) => client.updateRemoteVideoView(remoteUid, { ...canvas, x: 48 }),
  },
  {
    id: 'render.suspend-overlay',
    method: 'setNativeVideoOverlaySuspended',
    expectedParams: { suspended: false },
    requiredEvidence: ['response'],
    run: (client) => client.setNativeVideoOverlaySuspended(false),
  },
  {
    id: 'video.start-preview',
    method: 'startPreview',
    expectedParams: { sourceType: 0 },
    requiredEvidence: ['response', 'event'],
    run: (client) => client.startPreview(0),
  },
  {
    id: 'video.switch-camera',
    method: 'switchCamera',
    expectedParams: {},
    requiredEvidence: ['response'],
    run: async (client) => {
      await client.switchCamera();
      // Camera2 may still be finalizing the reopen path immediately after the
      // switch call resolves; give preview teardown a short settle window.
      await wait(500);
    },
  },
  {
    id: 'video.beauty',
    method: 'setBeautyEffectOptions',
    expectedParams: {
      enabled: true,
      options: {
        lighteningContrastLevel: 1,
        lighteningLevel: 0.5,
        smoothnessLevel: 0.4,
        rednessLevel: 0.3,
        sharpnessLevel: 0.2,
      },
      sourceType: 2,
    },
    requiredEvidence: ['response', 'error'],
    run: (client) => client.setBeautyEffectOptions(true, {
      lighteningContrastLevel: 1,
      lighteningLevel: 0.5,
      smoothnessLevel: 0.4,
      rednessLevel: 0.3,
      sharpnessLevel: 0.2,
    }, 2),
  },
  {
    id: 'video.content-inspect',
    method: 'enableContentInspect',
    expectedParams: { enabled: true, config: { module: 0, interval: 10 } },
    requiredEvidence: ['response'],
    run: (client) => client.enableContentInspect(true, { module: 0, interval: 10 }),
  },
  {
    id: 'mixing.start',
    method: 'startAudioMixing',
    expectedParams: { path: '<AUDIO_ASSET>', loopback: false, cycle: 1, startPos: 0 },
    requiredEvidence: ['response'],
    run: (client, context) => client.startAudioMixing({
      path: context.audioAssetPath,
      loopback: false,
      cycle: 1,
      startPos: 0,
    }),
  },
  {
    id: 'mixing.pause',
    method: 'pauseAudioMixing',
    expectedParams: {},
    requiredEvidence: ['response', 'error'],
    run: (client) => client.pauseAudioMixing(),
  },
  {
    id: 'mixing.resume',
    method: 'resumeAudioMixing',
    expectedParams: {},
    requiredEvidence: ['response', 'error'],
    run: (client) => client.resumeAudioMixing(),
  },
  {
    id: 'mixing.position-value',
    method: 'getAudioMixingCurrentPosition',
    expectedParams: {},
    requiredEvidence: ['value', 'error'],
    run: (client) => client.getAudioMixingCurrentPosition(),
  },
  {
    id: 'mixing.set-position',
    method: 'setAudioMixingPosition',
    expectedParams: { positionMs: 1000 },
    requiredEvidence: ['response', 'error'],
    run: (client) => client.setAudioMixingPosition(1000),
  },
  {
    id: 'mixing.adjust-volume',
    method: 'adjustAudioMixingVolume',
    expectedParams: { volume: 50 },
    requiredEvidence: ['response'],
    run: (client) => client.adjustAudioMixingVolume(50),
  },
  {
    id: 'effect.preload',
    method: 'preloadEffect',
    expectedParams: { soundId: 1, path: '<AUDIO_ASSET>', startPos: 250 },
    requiredEvidence: ['response'],
    run: (client, context) => client.preloadEffect(1, context.audioAssetPath, 250),
  },
  {
    id: 'effect.play',
    method: 'playEffect',
    expectedParams: {
      soundId: 1,
      path: '<AUDIO_ASSET>',
      loopCount: 1,
      pitch: 1,
      pan: 0,
      gain: 100,
      publish: false,
      startPos: 0,
    },
    requiredEvidence: ['response'],
    run: (client, context) => client.playEffect({
      soundId: 1,
      path: context.audioAssetPath,
      loopCount: 1,
      pitch: 1,
      pan: 0,
      gain: 100,
      publish: false,
      startPos: 0,
    }),
  },
  {
    id: 'effect.pause',
    method: 'pauseEffect',
    expectedParams: { soundId: 1 },
    requiredEvidence: ['response', 'error'],
    run: (client) => client.pauseEffect(1),
  },
  {
    id: 'effect.resume',
    method: 'resumeEffect',
    expectedParams: { soundId: 1 },
    requiredEvidence: ['response', 'error'],
    run: (client) => client.resumeEffect(1),
  },
  {
    id: 'effect.set-volume',
    method: 'setEffectsVolume',
    expectedParams: { volume: 65 },
    requiredEvidence: ['response'],
    run: (client) => client.setEffectsVolume(65),
  },
  {
    id: 'mixing.adjust-publish-volume',
    method: 'adjustAudioMixingPublishVolume',
    expectedParams: { volume: 70 },
    requiredEvidence: ['response', 'error'],
    run: (client) => client.adjustAudioMixingPublishVolume(70),
  },
  {
    id: 'mixing.adjust-playout-volume',
    method: 'adjustAudioMixingPlayoutVolume',
    expectedParams: { volume: 80 },
    requiredEvidence: ['response', 'error'],
    run: (client) => client.adjustAudioMixingPlayoutVolume(80),
  },
  {
    id: 'effect.stop',
    method: 'stopEffect',
    expectedParams: { soundId: 1 },
    requiredEvidence: ['response'],
    run: (client) => client.stopEffect(1),
  },
  {
    id: 'mixing.stop',
    method: 'stopAudioMixing',
    expectedParams: {},
    requiredEvidence: ['response'],
    run: (client) => client.stopAudioMixing(),
  },
  {
    id: 'video.stop-preview',
    method: 'stopPreview',
    expectedParams: { sourceType: 0 },
    requiredEvidence: ['response'],
    run: (client) => client.stopPreview(0),
  },
  {
    id: 'render.remove-remote-view',
    method: 'removeRemoteVideoView',
    expectedParams: { uid: remoteUid },
    requiredEvidence: ['response'],
    run: (client) => client.removeRemoteVideoView(remoteUid),
  },
  {
    id: 'render.remove-local-view',
    method: 'removeLocalVideoView',
    expectedParams: {},
    requiredEvidence: ['response'],
    run: (client) => client.removeLocalVideoView(),
  },
  {
    id: 'channel.leave',
    method: 'leaveChannel',
    expectedParams: {
      stopAudioMixing: true,
      stopAllEffect: true,
      unloadAllEffect: true,
      stopMicrophoneRecording: true,
    },
    requiredEvidence: ['response', 'event'],
    run: (client) => client.leaveChannel({
      stopAudioMixing: true,
      stopAllEffect: true,
      unloadAllEffect: true,
      stopMicrophoneRecording: true,
    }),
  },
  {
    id: 'engine.destroy',
    method: 'destroy',
    expectedParams: {},
    requiredEvidence: ['response'],
    run: (client) => client.destroy(),
  },
];
